from Tests import create_instance_test,general_test,search_instance_test,delete_instance_test,reset_collection_test,modify_instance_test

Test_general = general_test.Test_general
Test_create_instance = create_instance_test.Test_create_instance
Test_search_instance = search_instance_test.Test_search_instance
Test_delete_instance = delete_instance_test.Test_delete_instance
Test_reset_collection = reset_collection_test.Test_reset_all_collection
Test_modify_instance=modify_instance_test.Test_modify_instance